@startuml
Alice ->  Bob ++: Standard request
Bob --> Alice--: Standard Response
Alice -> Bob++: Standard request
Bob --> Alice--: Standard Response

Mallory -> Bob++: DoS attack

Alice -> Bob: Standard request
Alice -> Bob: Standard request

@enduml